-- Gold Data Vault 2.0 — Same-As Link: cross-source vacancy deduplication.
--
-- Identifies the same real-world vacancy appearing in multiple sources.
-- Silver content-hash dedup already removes byte-identical duplicates.
-- SAL handles semantic equivalents: same role at same company, different wording.
--
-- Strategy: blocking-only SQL (no LLM). Candidate pairs are generated by:
--   1. Same normalized company name (UPPER TRIM match across sources)
--   2. Published within 7 days of each other (or both dates NULL)
--   3. Different source systems
--
-- similarity_method = 'company_date_block' documents the detection method.
-- hub_vacancy_hk_1 < hub_vacancy_hk_2 (alphabetical) prevents duplicate pairs
-- (A,B) and (B,A) for the same match.
--
-- Currently yields 0 rows — TG and LinkedIn Silver are empty at Phase 3 completion.

WITH vacancy_with_company AS (
  -- Enrich silver.vacancies with normalized company name from each source table.
  -- TG posts have no company field — excluded from SAL blocking (no BK to match on).
  SELECT
    v.content_hash,
    v.source,
    v.published_at,
    v.published_at_approx,
    MD5(UPPER(TRIM(v.content_hash)))  AS hub_vacancy_hk,
    COALESCE(
      UPPER(TRIM(hh.employer_name)),
      UPPER(TRIM(li.company))
    )                                 AS company_name_norm
  FROM {{ ref('vacancies') }} v
  LEFT JOIN {{ ref('hh_vacancies') }} hh
    ON v.content_hash = hh.content_hash AND v.source = 'hh'
  LEFT JOIN {{ ref('linkedin_posts') }} li
    ON v.content_hash = li.content_hash AND v.source = 'linkedin'
  WHERE COALESCE(
    UPPER(TRIM(hh.employer_name)),
    UPPER(TRIM(li.company))
  ) IS NOT NULL
),
candidate_pairs AS (
  -- Self-join: find cross-source vacancies sharing the same company.
  -- Alphabetical ordering on hub_vacancy_hk ensures each pair appears exactly once.
  SELECT
    a.hub_vacancy_hk                                AS hub_vacancy_hk_1,
    b.hub_vacancy_hk                                AS hub_vacancy_hk_2,
    COALESCE(a.published_at, a.published_at_approx) AS pub_1,
    COALESCE(b.published_at, b.published_at_approx) AS pub_2
  FROM vacancy_with_company a
  JOIN vacancy_with_company b
    ON a.company_name_norm = b.company_name_norm
   AND a.source != b.source
   AND a.hub_vacancy_hk < b.hub_vacancy_hk
),
filtered_pairs AS (
  -- Apply date proximity filter: within 7 days, or both dates unknown.
  SELECT *
  FROM candidate_pairs
  WHERE
    (pub_1 IS NULL AND pub_2 IS NULL)
    OR ABS(DATEDIFF(CAST(pub_1 AS DATE), CAST(pub_2 AS DATE))) <= 7
)
SELECT
  MD5(CONCAT_WS('||', hub_vacancy_hk_1, hub_vacancy_hk_2))  AS sal_hk,
  hub_vacancy_hk_1,
  hub_vacancy_hk_2,
  'company_date_block'                                        AS similarity_method,
  current_timestamp()                                         AS load_dts
FROM filtered_pairs
